name: Deploy Feature

on:
  push:
    branches:
      - feature*

jobs:
  build:
    run-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-b9dfd182ccca4b00b0833133a-nonprodbucket-a0n8cz4f3arn
    steps:
      - name: check code
        uses: actions/checkout@v2
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1
      - name: setup nodejs
        uses: action/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: |
          npm ci
          npm run build
      - name: deplot files to bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read